natal_chart_interpretation_task:
  description: >
    Task: Analyze the provided natal chart data comprehensively, acting as a master astrologer preparing a detailed analytical brief.
    Context: Focus on dissecting core symbolic structures using the specific data points: planetary positions (sign, exact degree, house), aspects (note key conjunctions, oppositions, squares, trines, sextiles, quincunxes, and tight orbs), dignities/debilities (rulership, exaltation, detriment, fall, peregrine), sect (diurnal/nocturnal chart, planets in/out of sect), planetary motion (retrogrades), house cusps, chart shape (e.g., Bowl), and element/modality distributions.
    Methodology: Integrate Hellenistic, Psychological, and Humanistic perspectives. Identify and weight key factors like the chart ruler, Ascendant/MC rulers, the sect light (Sun/Moon), stellia, or out-of-bounds planets. Synthesize these elements to identify core themes, inherent strengths, potential challenges, and developmental pathways indicated in the chart. Explicitly interpret the symbolic meaning of the house placement for each planet. Analyze and contrast dominant vs. deficient elements and modalities, explaining the energetic implications. Illustrate significant dynamics with concrete psychological examples relevant to lived experience.
    Format: Structure the analysis logically with clear headings for each factor (e.g., "Sun in Cancer (29°15') in 5th House," "Moon-Uranus Conjunction in Scorpio (8th House)"). Provide detailed interpretive notes for each point, focusing on symbolic meaning and psychological potential. This output serves as the technical and interpretive foundation for the Natal Report Writer.
    The output must include:
    1. Chart Overview: Diurnal/Nocturnal status, Chart Shape, Sect Light condition, Element/Modality balance summary and interpretation.
    2. Core Identity Factors: In-depth analysis of Sun, Moon, Ascendant, and Midheaven (sign, house, degree, aspects, condition, rulers) including house symbolism interpretation.
    3. Planetary Placements & Condition: Detailed analysis for each planet (Mercury to Pluto, plus Chiron) covering: Sign, Exact Degree, House, Aspects (list significant ones), Dignities/Debilities, Sect status, Motion (Direct/Retrograde), interpretive notes synthesizing these factors, and explicit interpretation of the relevant house's life area.
    4. Key Aspect Analysis: Detailed interpretation of major aspect patterns (e.g., T-Squares, Grand Trines if present) and significant individual aspects (especially those involving luminaries or angles, or with tight orbs), describing the psychological dynamics involved.
    5. Synthesized Themes & Patterns: Identification and explanation of recurring motifs, major life themes, and energetic signatures derived from the overall analysis.
    6. Identified Strengths & Challenges: A summary of key potential strengths and developmental challenges indicated by the chart configurations.
    7. Notable Factors: Highlight and interpret any high-leverage points like the Chart Ruler's condition, stellia, intercepted houses/planets, critical degrees, Out-of-Bounds planets, etc.
    8. Psychological Examples: Concrete examples illustrating how key dynamics might manifest psychologically or in behavior.
    Subject's Name: {name}
    Today's date: {today}
    Natal Chart: {natal_chart}

  expected_output: >
    A detailed, structured analytical document providing a multi-layered interpretation of the natal chart data. 
  agent: natal_chart_interpreter


natal_report_writing_task:
  description: >
    Task: Transform the structured analytical output from the natal_chart_interpreter into a cohesive, engaging, and reader-friendly natal report narrative.
    Context: Utilize the detailed interpretation provided, targeting the individual whose chart was analyzed. Assume the reader may have little prior astrological knowledge.
    Methodology: Synthesize the technical analysis into a flowing, accessible narrative. Translate astrological concepts into clear, meaningful language, using metaphors, relatable real-world examples, and psychological insights. Ensure smooth transitions between sections, building a coherent story of the individual's potential. For each planetary placement, explicitly explain the significance of its house domain in practical life areas (e.g., relationships, career, self-expression, home life). Maintain a warm, empowering, and insightful tone throughout.
    Format/Structure: Craft the report following this structure:
    0. Title Block including the `[natal_chart]` placeholder:
        ```
        # Natal Chart for {name}
        Date of Report: {today}

        [natal_chart]

        **Date of Birth:** {date_of_birth}  
        **Place of Birth:** {place_of_birth}
        ```
    1. Introduction: A warm welcome, briefly explaining the purpose of a natal chart and introducing the core components (Sun, Moon, Ascendant) in an accessible way.
    2. The Core You: Deeper dives into the Sun, Moon, and Ascendant placements and their interplay, based on the interpreter's analysis.
    3. Your Planetary Toolkit: Sections for each planet (Mercury to Pluto, plus Chiron). For each:
    * Explain the planet's core archetype/function in simple terms.
    * Describe its expression through its Sign.
    * Crucially, explain the life area signified by its House placement and how the planet operates there.
    * Weave in the meaning of its most significant aspects in a narrative way.
    4. Key Life Themes & Dynamics: Synthesize the major aspect patterns and recurring themes identified by the interpreter into a discussion of central life lessons, strengths, and growth areas.
    5. Pathways to Potential: Offer reflective prompts or gentle suggestions for harnessing strengths and navigating challenges, derived from the analysis.
    6. Conclusion: A brief, encouraging summary.
    7. Glossary: Define all key astrological terms used in the report (e.g., Aspect, Sign, House, Retrograde, Dignity, elements, modalities, planet names).

  expected_output: >
    A complete, well-structured, and elegantly written natal report narrative. The report must be:
    * Reader-Focused: Written directly to the individual in a warm, accessible, and empowering tone.
    * Comprehensive: Covering all specified sections from Introduction to Glossary.
    * Interpretive: Translating the analytical points into meaningful psychological and life insights.
    * Practical: Clearly explaining house meanings in terms of real-life areas.
    * Cohesive: Flowing logically from one section to the next.
    * Accessible: Defining necessary jargon in a concluding glossary.
    The final output should feel both illuminating and grounding for the reader.
  agent: natal_report_writer