report_merging_task:
  description: >
    Task: Merge two independently written natal chart reports into one unified, high-quality report based on the same chart data.

    Context: Each report may differ in tone, depth, structure, or focus, but both are grounded in the same astronomical interpretation. Your task is to extract the strongest insights from each and synthesize them into a single, coherent narrative.

    Methodology:
    - Identify complementary or overlapping interpretations and consolidate them without duplication.
    - Where interpretations diverge, aim to integrate both perspectives wherever possible, enriching the section rather than replacing content.
      When selective inclusion is necessary, favor material that is:
        - More psychologically nuanced
        - Better grounded in the chart data
        - More emotionally resonant or practically applicable
    - Resolve tonal inconsistencies while maintaining a consistent, emotionally intelligent voice.
    - Preserve modular structure, symbolic clarity, and client-oriented insight throughout.

    Format/Structure:
    - Use the following markdown-based report structure:
      0. Title Block including the `[natal_chart]` placeholder:
        ```
        # Natal Chart for {name}
        Date of Report: {today}

        [natal_chart]

        **Date of Birth:** {date_of_birth}  
        **Place of Birth:** {place_of_birth}
        ``` 
      1. Introduction  
      2. Energetic Balance & Pattern Emphasis  
      3. Core Identity: The Big 3 (Ascendant, Sun, Moon)  
      4. Planetary Psychology and Celestial Dynamics  
      5. Aspects & Archetypal Dynamics  
      6. Eclipse and Syzygy Significance  
      7. House Emphasis  
      8. Psychological and Developmental Themes  
      9. Guidance and Reflections  
      10. Conclusion  
      11. Glossary

    - Do not invent new astrological placements or interpret outside of what exists in the provided reports.
    - Maintain clean markdown output with no code blocks.

    Report 1:
    {gpt_natal_analysis}

    Report 2:
    {gemini_natal_analysis}

  expected_output: >
    A single, merged natal chart report that draws on the best of both input reports, organized according to the specified structure, emotionally intelligent in tone, psychologically rich in content, and formatted cleanly in markdown.
  agent: report_merger
